# Generated by Django 5.0.2 on 2024-02-26 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitudCompra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Aprobado'), (0, 'Desaprobado')], null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicituds',
            field=models.ManyToManyField(through='SolicitudCompra.Solicitud_compra', to='SolicitudCompra.producto'),
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='solicitud',
        ),
    ]
