# Generated by Django 5.0.2 on 2024-02-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitudCompra', '0003_rename_producto_solicitud_compra_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
