# Generated by Django 5.0.2 on 2024-02-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitudCompra', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_compra',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
