# Generated by Django 5.0.2 on 2024-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitudCompra', '0006_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
